name: Deploy to GitHub Pages
# reference: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-workflow.yml'
      - './**'
  pull_request:
    types: [opened, reopened, labeled, synchronize, edited]
    paths:
      - '.github/workflows/deploy-workflow.yml'
      - './**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repo and setup node 🛎️
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install and build 🔧
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        # if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          full_commit_message: ${{ github.event.head_commit.message }}
          # enable_jekyll: false
